### ISSUE TITLE
Failed to load external module @babel/register

### ISSUE THREAD

**Issue by VladyslavDP** [ninelines-team/ninelines-docs#1]
после git-clone и gulp такая ошибка

21:55:20] Failed to load external module @babel/register
[21:55:20] Requiring external module babel-register
/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/home/home/WebstormProjects/tpl/project-template"
    at /home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/home/WebstormProjects/tpl/project-template/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)

**Comment by beliarh** [comment]
После `git clone` запускалась ли команда `npm install`?

**Comment by VladyslavDP** [comment]
да

**Comment by beliarh** [comment]
1. Устанавливались ли какие-то дополнительные библиотеки (`npm install ...`)?
2. Нужна информация об окружении, в котором воспроизводится баг: операционная система, версия node.js, версия npm, версия gulp и gulp-cli (установленные глобально).

**Comment by beliarh** [comment]
@VladyslavDP вышла новая версия сборки. babel-register теперь не используется напрямую. Повторяется ли проблема теперь?
